### ISSUE TITLE
Tailwind CSS Compatibility?

### ISSUE THREAD

**Issue by silicahd** [momentum81/php-remove-unused-css#1]
Thank you for posting this project, I was just looking for an alternative to purgecss that I can use in Laravel.   So far this seems to be the best option. 

Here is my dilema maybe you have some thoughts.   I am trying to pass in a vairaible that contains the HTML and than purge the unused Tailwind CSS code, at the end I am looking to export the left over CSS to a varaibe that I can save in the DB.

**Comment by BenGriffiths** [comment]
Does tailwind create regular CSS files once it's all setup? If so, I think the only requirement here would be to pass variables rather than just files to the processor. I'll look at adding that as a feature.

**Comment by silicahd** [comment]
In a way, tailwind does have a distribution code https://registry.npmjs.org/tailwindcss/-/tailwindcss-1.4.6.tgz see dis folder here, but it does use some odd classes. I am starting to look at this this weekend and see if I can get it to work.
